name: Website Agents
on:
  push:
    branches:
      - main
jobs:
  run-agents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Content Agent
        run: python agents/content_agent.py
      - name: Run UI/UX Agent
        run: python agents/uiux_agent.py
      - name: Run Consistency Agent
        run: python agents/consistency_agent.py
      - name: Run Transparency Agent
        run: python agents/transparency_agent.py
