name: site-audit
on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to audit"
        required: false
        default: "https://www.virtauto.de"
  schedule:
    - cron: "17 3 * * *"

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Lighthouse CI
        run: |
          npm i -g @lhci/cli@0.13.x

      - name: Run Lighthouse CI
        id: lhci
        run: |
          lhci collect --url "${{ inputs.url || 'https://www.virtauto.de' }}" --numberOfRuns=1 --collect.lighthouseFlags="--budgetsPath=./rules/lh-budgets.json" || true
          lhci upload --target=temporary-public-storage || true

      - name: Save report artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ".lighthouseci/*"

      - name: Emit basic telemetry
        run: |
          echo "{\"audit\":\"lighthouse\",\"url\":\"${{ inputs.url || 'https://www.virtauto.de' }}\"}" > ops/reports/site_audit_telemetry.json

      - name: Upload telemetry
        uses: actions/upload-artifact@v4
        with:
          name: site-audit-telemetry
          path: ops/reports/site_audit_telemetry.json
