name: content-ingest
on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"    # hourly

permissions:
  contents: write
  pull-requests: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser markdownify

      - name: Generate new posts from feed(s)
        id: gen
        env:
          FEEDS: https://medium.com/feed/@andreas-braun   # add more feeds by comma
        run: |
          import os, sys, time, pathlib, feedparser, hashlib
          from markdownify import markdownify as md
          root = pathlib.Path(".")
          outdir = root / "content" / "blog"
          outdir.mkdir(parents=True, exist_ok=True)

          feeds = [u.strip() for u in os.environ["FEEDS"].split(",") if u.strip()]
          created = []
          for url in feeds:
            d = feedparser.parse(url)
            for e in d.entries[:5]:
              title = e.get("title","Untitled")
              link  = e.get("link","")
              html  = e.get("content",[{"value": e.get("summary","")}])[0]["value"]
              body  = md(html)
              stamp = e.get("published","") or e.get("updated","")
              slug  = "-".join(title.lower().split())[:60]
              # dedupe by link hash
              h = hashlib.sha1(link.encode("utf-8")).hexdigest()[:8]
              fname = f"{time.strftime('%Y-%m-%d')}-{slug}-{h}.md"
              path = outdir / fname
              if path.exists(): 
                continue
              path.write_text(f"---\ntitle: \"{title}\"\nsource: \"{link}\"\n---\n\n{body}\n", encoding="utf-8")
              created.append(fname)

          open(os.environ.get("GITHUB_OUTPUT","/tmp/out"),"a").write(f"created={','.join(created)}\n")
        shell: python

      - name: Create Pull Request (if changes)
        if: steps.gen.outputs.created != ''
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(content): ingest new blog posts"
          title: "Content ingest: new posts"
          body: "Automated content ingest"
          branch: "auto/content-ingest"
          labels: content, automation
