name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *"   # Täglich um 03:00 Uhr

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build news from audit log
        working-directory: website/scripts
        run: |
          python build_news_from_audit.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
