name: Build & Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # täglich 03:00 Uhr

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build news.json from audit log (tolerant)
        working-directory: website/scripts
        run: |
          python build_news_from_audit.py || echo "News build skipped (no audit file)."

      - name: Upload website as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
