name: Self Agents
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: self-agents-${{ github.ref }}
  cancel-in-progress: false

jobs:
  audit:
    name: Self Audit
    uses: ./.github/workflows/self-audit.yml
    secrets: inherit

  guardian:
    name: Self Guardian
    needs: audit
    uses: ./.github/workflows/self-guardian.yml
    secrets: inherit

  optimization:
    name: Self Optimization
    needs: guardian
    uses: ./.github/workflows/self-optimization.yml
    secrets: inherit

  content:
    name: Self Content
    needs: optimization
    uses: ./.github/workflows/self-content.yml
    secrets: inherit
