name: Self Audit Agent

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Website URL"
        required: false
        default: "https://virtauto.de"
  schedule:
    - cron: "15 */6 * * *"   # alle 6h
  workflow_call: {}

permissions:
  contents: write

jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt

      - name: Run audit
        run: |
          python -m scripts.self_audit \
            --url "${{ github.event.inputs.url || 'https://virtauto.de' }}" \
            --out ops/reports/self_audit.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: self-audit-report
          path: ops/reports/self_audit.json
